matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx

script:
  - pip install cibuildwheel==0.1.3 pybind11==2.1.0
  - cibuildwheel --output-dir wheelhouse


# language: cpp
# compiler:
#   - gcc
#   - clang
# os:
#   - linux
#   - osx
# dist: trusty

# script: "make pcst_fast_test && ./pcst_fast_test"

# notifications:
#   recipients:
#     - ludwigschmidt2@gmail.com
#   email:
#     on_success: never
#     on_failure: change
