matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx

script:
  - pip install git+https://github.com/joerick/cibuildwheel@2c0d6e3db1590a9f6902c6d46a8ff27aeb4f1add pybind11
  - cibuildwheel --output-dir wheelhouse

env:
  global:
    - CIBW_BEFORE_BUILD="pip install pybind11"

# language: cpp
# compiler:
#   - gcc
#   - clang
# os:
#   - linux
#   - osx
# dist: trusty

# script: "make pcst_fast_test && ./pcst_fast_test"

# notifications:
#   recipients:
#     - ludwigschmidt2@gmail.com
#   email:
#     on_success: never
#     on_failure: change
