matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx

script:
  - pip install git+https://github.com/joerick/cibuildwheel@d5fa5475d4e8c58000d056f44a9968f68337cf95
  - cibuildwheel --output-dir wheelhouse

env:
  global:
    - CIBW_BEFORE_BUILD="{pip} install pybind11"
    - CIBW_SKIP=cp26-*

# language: cpp
# compiler:
#   - gcc
#   - clang
# os:
#   - linux
#   - osx
# dist: trusty

# script: "make pcst_fast_test && ./pcst_fast_test"

# notifications:
#   recipients:
#     - ludwigschmidt2@gmail.com
#   email:
#     on_success: never
#     on_failure: change
